import type { Key } from 'ink'

import type { Action } from '~/utils/types'

type KeyMatcher = (input: string, key: Key) => boolean

type ShortcutEffect = { type: 'dispatch'; action: Action } | { type: 'exit' }

export interface Shortcut {
    id: string
    mode: 'browser' | 'global'
    keyLabel: string
    description: string
    helpDescription: string
    match: KeyMatcher
    effect: ShortcutEffect
    keyDef: string | string[]
    sequence?: string
    helpKey?: string
}

export interface HelpItem {
    key: string
    description: string
    helpDescription: string
    effect: ShortcutEffect
}

export function getHelpItems(shortcuts: Shortcut[]): HelpItem[] {
    return shortcuts
        .filter((s) => s.helpKey !== undefined)
        .map((s) => ({
            key: s.helpKey!,
            description: s.description,
            helpDescription: s.helpDescription,
            effect: s.effect,
        }))
}

export const defaultKeymap: Shortcut[] = [
    // Global
    {
        id: 'quit',
        mode: 'global',
        keyLabel: '',
        description: 'quit',
        helpDescription: 'Quit application',
        keyDef: 'q',
        helpKey: 'q',
        match: (input) => input === 'q',
        effect: { type: 'exit' },
    },

    // Browser mode
    {
        id: 'moveUp',
        mode: 'browser',
        keyLabel: '',
        description: 'navigate',
        helpDescription: 'Move cursor up',
        keyDef: ['k', 'up'],
        helpKey: 'k/↑',
        match: (input, key) => key.upArrow || input === 'k',
        effect: {
            type: 'dispatch',
            action: { type: 'MOVE_CURSOR', direction: 'up' },
        },
    },
    {
        id: 'moveDown',
        mode: 'browser',
        keyLabel: '',
        description: 'navigate',
        helpDescription: 'Move cursor down',
        keyDef: ['j', 'down'],
        helpKey: 'j/↓',
        match: (input, key) => key.downArrow || (input === 'j' && !key.shift),
        effect: {
            type: 'dispatch',
            action: { type: 'MOVE_CURSOR', direction: 'down' },
        },
    },
    {
        id: 'goToBottom',
        mode: 'browser',
        keyLabel: '',
        description: 'go to bottom',
        helpDescription: 'Jump to last entry',
        keyDef: 'G',
        helpKey: 'G',
        match: (input) => input === 'G',
        effect: {
            type: 'dispatch',
            action: { type: 'MOVE_CURSOR', direction: 'bottom' },
        },
    },
    {
        id: 'goToTop',
        mode: 'browser',
        keyLabel: '',
        description: 'go to top',
        helpDescription: 'Jump to first entry',
        keyDef: 'gg',
        helpKey: 'gg',
        sequence: 'gg',
        match: () => false,
        effect: {
            type: 'dispatch',
            action: { type: 'MOVE_CURSOR', direction: 'top' },
        },
    },
    {
        id: 'focusLeft',
        mode: 'browser',
        keyLabel: '',
        description: 'focus left panel',
        helpDescription: 'Focus left panel',
        keyDef: 'H',
        helpKey: 'H',
        match: (input) => input === 'H',
        effect: {
            type: 'dispatch',
            action: { type: 'FOCUS_PANEL', panel: 'left' },
        },
    },
    {
        id: 'focusRight',
        mode: 'browser',
        keyLabel: '',
        description: 'focus right panel',
        helpDescription: 'Focus right panel',
        keyDef: 'L',
        helpKey: 'L',
        match: (input) => input === 'L',
        effect: {
            type: 'dispatch',
            action: { type: 'FOCUS_PANEL', panel: 'right' },
        },
    },
    {
        id: 'switchPanel',
        mode: 'browser',
        keyLabel: '',
        description: 'switch panel',
        helpDescription: 'Switch panel focus',
        keyDef: 'tab',
        helpKey: 'Tab',
        match: (_input, key) => key.tab,
        effect: { type: 'dispatch', action: { type: 'SWITCH_PANEL' } },
    },
    {
        id: 'expandOrOpen',
        mode: 'browser',
        keyLabel: '',
        description: 'expand/collapse',
        helpDescription: 'Expand directory or enter file',
        keyDef: ['l', 'right'],
        helpKey: 'l/→',
        match: (input, key) => input === 'l' || key.rightArrow,
        effect: { type: 'dispatch', action: { type: 'NAVIGATE_INTO' } },
    },
    {
        id: 'openDiff',
        mode: 'browser',
        keyLabel: '',
        description: 'open diff',
        helpDescription: 'Open unified diff view',
        keyDef: 'enter',
        helpKey: 'Enter',
        match: (_input, key) => key.return,
        effect: { type: 'dispatch', action: { type: 'OPEN_DIFF' } },
    },
    {
        id: 'collapse',
        mode: 'browser',
        keyLabel: '',
        description: 'collapse',
        helpDescription: 'Collapse directory or go to parent',
        keyDef: ['h', 'left', 'backspace', 'delete'],
        helpKey: 'h/←',
        match: (input, key) =>
            key.backspace
            || key.delete
            || (input === 'h' && !key.shift)
            || key.leftArrow,
        effect: { type: 'dispatch', action: { type: 'COLLAPSE_PARENT' } },
    },
    {
        id: 'expandAll',
        mode: 'browser',
        keyLabel: '',
        description: 'expand all',
        helpDescription: 'Expand all directories',
        keyDef: 'zR',
        helpKey: 'zR',
        sequence: 'zR',
        match: () => false,
        effect: { type: 'dispatch', action: { type: 'EXPAND_ALL' } },
    },
    {
        id: 'collapseAll',
        mode: 'browser',
        keyLabel: '',
        description: 'collapse all',
        helpDescription: 'Collapse all directories',
        keyDef: 'zM',
        helpKey: 'zM',
        sequence: 'zM',
        match: () => false,
        effect: { type: 'dispatch', action: { type: 'COLLAPSE_ALL' } },
    },
    {
        id: 'halfPageDown',
        mode: 'browser',
        keyLabel: '',
        description: 'half page down',
        helpDescription: 'Scroll half page down',
        keyDef: 'ctrl+d',
        helpKey: 'Ctrl+d',
        match: (input, key) => key.ctrl && input === 'd',
        effect: {
            type: 'dispatch',
            action: { type: 'MOVE_CURSOR', direction: 'down' },
        },
    },
    {
        id: 'halfPageUp',
        mode: 'browser',
        keyLabel: '',
        description: 'half page up',
        helpDescription: 'Scroll half page up',
        keyDef: 'ctrl+u',
        helpKey: 'Ctrl+u',
        match: (input, key) => key.ctrl && input === 'u',
        effect: {
            type: 'dispatch',
            action: { type: 'MOVE_CURSOR', direction: 'up' },
        },
    },
    {
        id: 'fullPageDown',
        mode: 'browser',
        keyLabel: '',
        description: 'full page down',
        helpDescription: 'Scroll full page down',
        keyDef: 'ctrl+f',
        helpKey: 'Ctrl+f',
        match: (input, key) => key.ctrl && input === 'f',
        effect: {
            type: 'dispatch',
            action: { type: 'MOVE_CURSOR', direction: 'down' },
        },
    },
    {
        id: 'fullPageUp',
        mode: 'browser',
        keyLabel: '',
        description: 'full page up',
        helpDescription: 'Scroll full page up',
        keyDef: 'ctrl+b',
        helpKey: 'Ctrl+b',
        match: (input, key) => key.ctrl && input === 'b',
        effect: {
            type: 'dispatch',
            action: { type: 'MOVE_CURSOR', direction: 'up' },
        },
    },
    {
        id: 'nextDiff',
        mode: 'browser',
        keyLabel: '',
        description: 'next diff',
        helpDescription: 'Jump to next difference',
        keyDef: ']c',
        helpKey: ']c',
        sequence: ']c',
        match: () => false,
        effect: {
            type: 'dispatch',
            action: { type: 'JUMP_TO_DIFF', direction: 'next' },
        },
    },
    {
        id: 'prevDiff',
        mode: 'browser',
        keyLabel: '',
        description: 'prev diff',
        helpDescription: 'Jump to previous difference',
        keyDef: '[c',
        helpKey: '[c',
        sequence: '[c',
        match: () => false,
        effect: {
            type: 'dispatch',
            action: { type: 'JUMP_TO_DIFF', direction: 'prev' },
        },
    },
    {
        id: 'yankPath',
        mode: 'browser',
        keyLabel: '',
        description: 'yank path',
        helpDescription: 'Copy file path to clipboard',
        keyDef: 'y',
        helpKey: 'y',
        match: (input) => input === 'y',
        effect: { type: 'dispatch', action: { type: 'YANK_PATH' } },
    },
    {
        id: 'contextMenu',
        mode: 'browser',
        keyLabel: '.',
        description: 'actions',
        helpDescription: 'Open actions menu',
        keyDef: '.',
        helpKey: '.',
        match: (input) => input === '.',
        effect: { type: 'dispatch', action: { type: 'SHOW_CONTEXT_MENU' } },
    },
    {
        id: 'preferences',
        mode: 'browser',
        keyLabel: ',',
        description: 'preferences',
        helpDescription: 'Open preferences',
        keyDef: ',',
        helpKey: ',',
        match: (input) => input === ',',
        effect: { type: 'dispatch', action: { type: 'TOGGLE_PREFERENCES' } },
    },
    {
        id: 'search',
        mode: 'browser',
        keyLabel: '/',
        description: 'filter',
        helpDescription: 'Filter entries by name',
        keyDef: '/',
        helpKey: '/',
        match: (input) => input === '/',
        effect: { type: 'dispatch', action: { type: 'OPEN_SEARCH' } },
    },
    {
        id: 'toggleFilter',
        mode: 'browser',
        keyLabel: 'f',
        description: 'diff only',
        helpDescription: 'Toggle diff-only filter',
        keyDef: 'f',
        helpKey: 'f',
        match: (input) => input === 'f',
        effect: { type: 'dispatch', action: { type: 'TOGGLE_FILTER' } },
    },
    {
        id: 'toggleIgnore',
        mode: 'browser',
        keyLabel: '',
        description: 'toggle ignore',
        helpDescription: 'Toggle ignore filtering',
        keyDef: 'zi',
        helpKey: 'zi',
        sequence: 'zi',
        match: () => false,
        effect: { type: 'dispatch', action: { type: 'TOGGLE_IGNORE' } },
    },
    {
        id: 'quickIgnore',
        mode: 'browser',
        keyLabel: 'i',
        description: 'ignore entry',
        helpDescription: 'Quick-add entry to ignore',
        keyDef: 'i',
        helpKey: 'i',
        match: (input, key) => input === 'i' && !key.shift,
        effect: { type: 'dispatch', action: { type: 'SHOW_QUICK_IGNORE' } },
    },
    {
        id: 'ignorePatterns',
        mode: 'browser',
        keyLabel: 'I',
        description: 'ignore patterns',
        helpDescription: 'Manage ignore patterns',
        keyDef: 'I',
        helpKey: 'I',
        match: (input) => input === 'I',
        effect: { type: 'dispatch', action: { type: 'SHOW_IGNORE_DIALOG' } },
    },
    {
        id: 'copyToRight',
        mode: 'browser',
        keyLabel: '>/<',
        description: 'copy to right',
        helpDescription: 'Copy entry to right side',
        keyDef: '>',
        helpKey: '>',
        match: (input) => input === '>',
        effect: { type: 'dispatch', action: { type: 'COPY_TO_RIGHT' } },
    },
    {
        id: 'copyToLeft',
        mode: 'browser',
        keyLabel: '',
        description: 'copy to left',
        helpDescription: 'Copy entry to left side',
        keyDef: '<',
        helpKey: '<',
        match: (input) => input === '<',
        effect: { type: 'dispatch', action: { type: 'COPY_TO_LEFT' } },
    },
    {
        id: 'delete',
        mode: 'browser',
        keyLabel: 'd',
        description: 'delete',
        helpDescription: 'Delete selected entry',
        keyDef: 'd',
        helpKey: 'd',
        match: (input) => input === 'd',
        effect: { type: 'dispatch', action: { type: 'CONFIRM_DELETE' } },
    },
    {
        id: 'refresh',
        mode: 'browser',
        keyLabel: 'r',
        description: 'refresh',
        helpDescription: 'Refresh directory comparison',
        keyDef: 'r',
        helpKey: 'r',
        match: (input) => input === 'r',
        effect: { type: 'dispatch', action: { type: 'REFRESH' } },
    },
    {
        id: 'swapPanels',
        mode: 'browser',
        keyLabel: 'S',
        description: 'swap panels',
        helpDescription: 'Swap left and right panels',
        keyDef: 'S',
        helpKey: 'S',
        match: (input) => input === 'S',
        effect: { type: 'dispatch', action: { type: 'SWAP_PANELS' } },
    },
    {
        id: 'showHelp',
        mode: 'browser',
        keyLabel: '?',
        description: 'keybindings',
        helpDescription: 'Show all keybindings',
        keyDef: '?',
        helpKey: '?',
        match: (input) => input === '?',
        effect: { type: 'dispatch', action: { type: 'SHOW_HELP' } },
    },
    {
        id: 'editKeybindings',
        mode: 'browser',
        keyLabel: 'K',
        description: 'edit keybindings',
        helpDescription: 'Open keybindings editor',
        keyDef: 'K',
        helpKey: 'K',
        match: (input) => input === 'K',
        effect: {
            type: 'dispatch',
            action: { type: 'SHOW_KEYBINDINGS_EDITOR' },
        },
    },
]
